site_name: Trabalho 1 - Engenharia de Dados
site_description: Documentação sobre Spark, Apache Iceberg e Delta Lake
theme:
  name: material
  language: pt-BR
  palette:
    primary: blue
    accent: cyan
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
nav:
  - Início: index.md
  - Contextualização: contextualizacao.md
  - Exemplos de código: exemplos_codigo.md
  - Modelagem e Testes: modelagem_e_testes.md
  - Spark: spark.md
  - Iceberg: iceberg.md
  - Delta Lake: delta.md
